name: Coding Standards
on:
  pull_request:
  push:
    branches: [main]

jobs:
  phpcs:
    name: PHP CS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP v8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: npm install
     - name: Run PHP CS Fixer
        args: --config=.php_cs.dist.php --allow-risky=yes

  eslint:
    name: ES Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP v8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: npm install
      - name: ESLINT
        run: ./node_modules/.bin/eslint resources/js/ Modules/*/Resources/assets/js/ --ext .js,.vue

  larastan:
    name: Larastan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP v8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: npm install
      - name: Setup env file
        run: cp .env.example .env
      - name: Configure application encryption key
        run: php artisan key:generate
      - name: Larastan
        run: ./vendor/bin/phpstan analyse
